# -*- coding: utf-8 -*-
"""App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fKSTYpIaS42jeBuywtyI5HrzAP8sJ10b
"""

import streamlit as st
import pandas as pd
import joblib

st.title("NBA 5-Year Career Prediction (Logistic Regression)")

# Load model
try:
    model = joblib.load("model.joblib")
except Exception as e:
    st.error("Could not load model.joblib. Make sure it's in the same folder as app.py.")
    st.stop()

# Optional: load dataset for preview & to auto-fill inputs
example = None
try:
    example = pd.read_csv("nba_logreg.csv")
    st.subheader("Dataset preview")
    st.write(example.head())
    # prepare example for defaults
    example = example.drop(columns=["Name"], errors="ignore")
    example = example.fillna(example.mean(numeric_only=True))
except Exception:
    example = None
    st.info("No nba_logreg.csv found (optional). You can still enter inputs manually.")

# build feature list
if example is not None:
    features = [c for c in example.columns if c != "TARGET_5Yrs"]
else:
    # fallback - if you know features list, paste it here as a list of strings
    st.error("Please upload nba_logreg.csv to the app folder OR edit app.py to list expected feature names.")
    st.stop()

st.subheader("Enter player stats")
user_input = {}
for col in features:
    default = float(example[col].mean()) if example is not None and col in example.columns else 0.0
    user_input[col] = st.number_input(col, value=default)

if st.button("Predict"):
    X_new = pd.DataFrame([user_input])
    try:
        pred = model.predict(X_new)[0]
        result = "Likely 5-Year Career" if int(pred) == 1 else "Not Likely"
        st.success(f"Prediction: **{result}**")
    except Exception as e:
        st.error(f"Prediction error: {e}")